# Generated by Django 4.2.7 on 2024-01-02 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iniadmatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='iniadmatch.teacher'),
        ),
    ]
