# Generated by Django 4.2.7 on 2024-01-04 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iniadmatch', '0004_alter_schedule_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='teacher',
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='routine',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='iniadmatch.routine'),
        ),
    ]
